# Generated by Django 2.2.7 on 2020-02-02 06:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public_Facility_MODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p27_001', models.CharField(max_length=10, verbose_name='行政区域コード')),
                ('p27_002', models.CharField(max_length=10, verbose_name='公共施設大分類')),
                ('p27_003', models.CharField(max_length=10, verbose_name='公共施設小分類')),
                ('p27_004', models.CharField(max_length=10, verbose_name='文化施設分類')),
                ('p27_005', models.CharField(max_length=254, verbose_name='名称')),
                ('p27_006', models.CharField(max_length=254, verbose_name='所在地')),
                ('p27_007', models.IntegerField(verbose_name='管理者コード')),
                ('p27_008', models.IntegerField(verbose_name='階数')),
                ('p27_009', models.IntegerField(verbose_name='建築年')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=6668)),
            ],
        ),
        migrations.CreateModel(
            name='RailRoadSection_info_MODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n02_001', models.CharField(max_length=1024, verbose_name='鉄道区分')),
                ('n02_002', models.CharField(max_length=1024, verbose_name='事業者種別')),
                ('n02_003', models.CharField(max_length=1024, verbose_name='路線名')),
                ('n02_004', models.CharField(max_length=1024, verbose_name='運営会社')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=6668)),
            ],
        ),
        migrations.CreateModel(
            name='Station_Info_MODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n02_001', models.CharField(max_length=1024, verbose_name='鉄道区分')),
                ('n02_002', models.CharField(max_length=1024, verbose_name='事業者種別')),
                ('n02_003', models.CharField(max_length=1024, verbose_name='路線名')),
                ('n02_004', models.CharField(max_length=1024, verbose_name='運営会社')),
                ('n02_005', models.CharField(max_length=1024, verbose_name='駅名')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=6668)),
            ],
        ),
    ]
